language: python
sudo: false

matrix:
  include:
    - python: 3.7
      dist: xenial  # https://github.com/travis-ci/travis-ci/issues/9815
      sudo: true

# install other libraries using pip
install:
  - pip install -U setuptools coveralls
  - pip install -Ue .[dev]

# command to run tests
script:
  - pytest
  - coveralls
